version: 2.1

# Define the jobs we want to run for this project
jobs:
  unit_test:
    docker:
      - image: alpine:latest
    steps:
      - apk add cmake make clang build-base llvm-static llvm-dev clang-static clang-dev
      - checkout
      - run: mkdir build && cd build
      - run: cmake ..
      - run: make cpp_dummy_test
      - run: ./cpp_dummy_test

# Orchestrate our job run sequence
workflows:
  test:
    jobs:
      - unit_test