version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  unit_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add git cmake make clang build-base llvm-static llvm-dev clang-static clang-dev
      - checkout
      - run: cmake .
      - run: make cpp_dummy_test
      - run: ./cpp_dummy_test
  sonar_scan:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add git cmake make clang build-base llvm-static llvm-dev clang-static clang-dev
      - checkout
      - run: cmake .
      - run: make cpp_dummy_test
      - sonarcloud/scan

workflows:
  ci:
    jobs:
      - unit_test
      - sonar_scan:
          context: SonarCloud
