version: 2.1

jobs:
  unit_test:
    docker:
      - image: jroddev/docker-debian-cmake-sonar:latest
    steps:
      - checkout
      - run: cmake .
      - run: make cpp_dummy_test
      - run: ./cpp_dummy_test
  sonar_scan:
    docker:
      - image: jroddev/docker-debian-cmake-sonar:latest
    steps:
      - checkout
      - run: cmake .
      - run:
          name: Build with wrapper
          command: sonar-build-wrapper --out-dir build_wrapper_output_directory make all
      - run:
          name: Sonar Scan
          command: SONAR_TOKEN=$SONAR_TOKEN /opt/sonar-scanner/bin/sonar-scanner
workflows:
  testing:
    jobs:
      - unit_test
  analysis:
    jobs:
      - sonar_scan:
          context: SonarCloud
