version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  unit_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add git cmake make clang build-base llvm-static llvm-dev clang-static clang-dev
      - checkout
      - run: cmake .
      - run: make cpp_dummy_test
      - run: ./cpp_dummy_test
  sonar_scan:
    docker:
      - image: debian:buster
    steps:
      - run: apt-get update
      - run: apt-get install -y build-essential git cmake autoconf libtool pkg-config curl unzip
      - checkout
      - run:
          name: Install Sonar Build Wrapper
          command: ./bin/sonar/install-build-wrapper-linux.sh
      - run: cmake .
      - run:
          name: Build with wrapper
          command: ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory make cpp_dummy_test
      - sonarcloud/scan

workflows:
  testing:
    jobs:
      - unit_test
  analysis:
    jobs:
      - sonar_scan:
          context: SonarCloud
