version: 2.1

jobs:
  unit_test:
    docker:
      - image: alpine:latest
    working_directory: /app
    steps:
      - run: apk add git cmake make clang build-base llvm-static llvm-dev clang-static clang-dev
      - checkout
      - run: mkdir build && cd build
      - run: echo "working dir $PWD"
      - run:
          command: cmake ..
          working_directory: /app/cpp-dummy/build
      - run: make cpp_dummy_test
      - run: ./cpp_dummy_test

workflows:
  test:
    jobs:
      - unit_test