version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  unit_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add git cmake make gcc build-base curl
      - checkout
      - run: cmake .
      - run: make cpp_dummy_test
      - run: ./cpp_dummy_test
  sonar_scan:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add git cmake make gcc build-base curl
      - checkout
      - run:
          name: Install Sonar Build Wrapper
          command: ./bin/sonar/install-build-wrapper-linux.sh
      - run: cmake .
      - run:
          name: Build with wrapper
          command: ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory make all
      - sonarcloud/scan

workflows:
  testing:
    jobs:
      - unit_test
  analysis:
    jobs:
      - sonar_scan:
          context: SonarCloud
